[package]
name = "pion"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
dashmap = "6.1.0"
env_logger = "0.11.8"
rsbinder = { version = "0.5.0", features = ["tokio"] }

[build-dependencies]
rsbinder-aidl = "0.5.0"

[dev-dependencies]
directories = "6.0.0"
